language: node_js
node_js: 12.14.1

stages:
  - name: test
    if: branch = master

jobs:
  include:
    - stage: test
  language: node_js
  node_js: 12.14.1
  install:
    - yarn install
    - npm install codecov -g
  script:
    - yarn lint
    - yarn test --coverage
  after_success:
    - codecov
