language: node_js
node_js: 12.14.1
stages:
  - name: test
    if: type = pull_request AND branch = master
  - name: deploy
    if: type != pull_request AND branch = master
addons:
  ssh_known_hosts: nataliabraz.dev
before_install:
  - openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv -in travis_rsa.enc -out travis_rsa -d
  - chmod 600 travis_rsa
  - mv travis_rsa ~/.ssh/id_rsa
jobs:
  include:
  - stage: test
    name: "Unit Tests"
    install:
      - yarn install
      - yarn global add codecov
    script:
      - yarn lint
      - yarn test --coverage
    after_success:
      - codecov
  - stage: deploy
    name: "Deploy"
    before_install:
      - rm -rf node_modules
    after_success:
      - bash ./scripts/deploy.sh
