language: node_js
node_js: 12.14.1
os: osx

stages:
  - name: test
    if: branch = master

jobs:
  include:
    - stage: test
      language: node_js
      node_js: 12.14.1
      install:
        - rm -rf node_modules
        - yarn install
        - yarn global add codecov
      script:
        - yarn lint
        - yarn test --coverage
      after_success:
        - codecov
